import type { Config } from "jest";
import nextJest from "next/jest.js";

const createJestConfig = nextJest({
  // Provide the path to your Next.js app to load next.config.js and .env files in your test environment
  dir: "./",
});

// Add any custom config to be passed to Jest
const config: Config = {
  coverageProvider: "v8",
  testEnvironment: "jest-environment-jsdom",
  setupFilesAfterEnv: ["<rootDir>/jest.setup.ts"],
  // The first three hold node:test suites, not Jest ones — they run under
  // `npm run test:eslint-rules` and `npm run test:scripts`. `.claude/` is
  // generated by `sync-ai` and also hosts agent worktrees, which are whole second
  // checkouts of this repo: collecting their tests turns 151 local tests into 503
  // and fails the gate on code that is not in this diff. CI clones fresh and never
  // sees them, so without this `ci:local` does not reproduce CI.
  testPathIgnorePatterns: [
    "<rootDir>/eslint-rules/",
    "<rootDir>/scripts/",
    "<rootDir>/pm-course/",
    "<rootDir>/.claude/",
  ],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/$1",
  },
  collectCoverageFrom: [
    "components/**/*.{ts,tsx}",
    "lib/**/*.{ts,tsx}",
    "app/**/*.{ts,tsx}",
    "!components/ui/**/*.tsx", // Focus on custom app components, not generic ui wrappers right now
    "!**/*.d.ts",
    "!**/node_modules/**",
  ],
};

// createJestConfig is exported this way to ensure that next/jest can load the Next.js config which is async
export default createJestConfig(config);
